activation: relu
batch_size: 16
beta_max: 50.0
beta_min: 0.1
channels: 64
color_mode: rgb
corrector: none
d_apply_batchnorm: false
d_channels:
- 64
- 128
- 256
- 256
d_drop_prob: 0.3
d_kernel_size: 5
d_lr: 0.0001
d_output_activation: null
d_steps: 3
dataset_name: celeba
drop_prob: null
embed_dim: 256
epochs: 100
eval_freq: 1
g_apply_batchnorm: true
g_channels:
- 256
- 256
- 256
- 128
g_drop_prob: null
g_first_dense_size: 128
g_kernel_size: 5
g_lr: 0.0001
g_output_activation: tanh
g_upmode: upconv
gp_weight: 1
image_range:
- 0
- 1
image_shape:
- 64
- 64
- 3
image_size: 64
kernel_size: 3
label_sigma: 0.05
latent_dim: 64
likelihood_weighting: false
lr: 0.0002
model_name: score
n_steps_each: 1
noise_removal: true
normalization: batch
num_plot_img: 16
num_scales: 1000
patch_size: null
predictor: euler_maruyama
probability_flow: false
reduce_mean: false
sampling_method: pc
save_freq: 10
score_backbone: NCSNv2
sde: simple
seed: 1234
sigma: 25.0
sigma_max: 90.0
sigma_min: 0.01
snr: 0.17
upmode: upconv
