activation: relu
batch_size: 16
beta_max: 50.0
beta_min: 0.1
channels: 64
color_mode: rgb
corrector: none
dataset_name: mnist
drop_prob: null
embed_dim: 256
epochs: 100
eval_freq: 1
image_range:
- 0
- 1
image_shape:
- 64
- 64
- 3
image_size: 64
kernel_size: 3
likelihood_weighting: false
lr: 0.0002
model_name: score
n_steps_each: 1
noise_removal: true
normalization: batch
num_plot_img: 16
num_scales: 1000
patch_size: null
predictor: euler_maruyama
probability_flow: false
reduce_mean: false
sampling_method: pc
save_freq: 10
score_backbone: NCSNv2
sde: simple
seed: 1234
sigma: 25.0
sigma_max: 90.0
sigma_min: 0.01
snr: 0.17
upmode: upconv
