K: 18
L: 4
batch_size: 16
clipnorm: 5
color_mode: rgb
coupling: affine
dataset_name: celeba
device: cuda
epochs: 1000
eval_freq: 1
image_range:
- 0
- 1
image_shape:
- 64
- 64
- 3
image_size: 64
last_zeros: true
log_freq: 100
lr: 0.0001
lr_factor: 0.5
lr_min: 1.0e-08
lr_patience: 1000
model_name: glow
n_bits_x: 5
num_img: 16
patch_size: null
save_freq: 1
seed: 1234
warmup_iter: 10000
