## Inference parameters
# path to data root
data_root: .\data
# dataset
run_name: mnist
# checkpoints
run_id:
  sgm: ./checkpoints/mnist/sgm
  glow: ./checkpoints/mnist/glow
  gan: ./checkpoints/mnist/gan
# device
device: 0
# random seed
seed: 1234
# number of images to process
num_img: 5
# keep track of images in each iteration and animate at the end
keep_track: true
# standard deviation of additive white gaussian noise
noise_stddev: 0.3
# type of corruption
corruptor: gaussian
# whether to corrupt data and use as pairs or assume data is corrupted
paired_data: true
# plot zoomed in version as well (provide coordinates here as list, (x, y, size))
zoom: null

metrics:
  - psnr
  - ssim
models:
  - bm3d
  - nlm
  - glow
  - sgm


sgm:
  lambda_coeff: 0.1
  # number of noise scales (i.e. time steps in SDE)
  num_scales: 200
  sde: simple
  sigma: 25
  sampling_method: pc
  predictor: euler_maruyama
  corrector: none
  guidance: projection

glow:
  lambda_coeff: 0.5
  step_size: 0.1
  num_steps: 200
  prior: z
  optim: adam
  init_std: 0.7
  init_strat: random

gan:
  lambda_coeff: 20
  step_size: 0.1
  num_steps: 300
  prior: z_squared
